[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 115200
extra_scripts = pre:scripts/load_env.py
lib_deps =
  madhephaestus/ESP32Servo
